steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/stark-tech/${REPO_NAME}/${BRANCH_NAME}/${COMMIT_SHA}',
        '.',
      ]
    env:
      - 'API_KEY_PREFIX=$_API_KEY_PREFIX'
      - 'EMAIL_FROM=$_EMAIL_FROM'
      - 'EMAIL_SERVER_HOST=$_EMAIL_SERVER_HOST'
      - 'EMAIL_SERVER_PORT=$_EMAIL_SERVER_PORT'
      - 'NEXT_PUBLIC_EMBED_LIB_URL=$_NEXT_PUBLIC_EMBED_LIB_URL'
      - 'NEXT_PUBLIC_WEBAPP_URL=$_NEXT_PUBLIC_WEBAPP_URL'
      - 'NEXT_PUBLIC_WEBSITE_URL=$_NEXT_PUBLIC_WEBSITE_URL'
      - 'NEXTAUTH_COOKIE_DOMAIN=$_NEXTAUTH_COOKIE_DOMAIN'
      - 'NEXTAUTH_URL=$_NEXTAUTH_URL'
    secretEnv:
      [
        'CALENDSO_ENCRYPTION_KEY',
        'DATABASE_URL',
        'EMAIL_SERVER_PASSWORD',
        'EMAIL_SERVER_USER',
        'GOOGLE_API_CREDENTIALS',
        'NEXTAUTH_SECRET',
        'CRON_API_KEY',
        'ZOOM_CLIENT_ID',
        'ZOOM_CLIENT_SECRET',
      ]
    availableSecrets:
      secretManager:
        - versionName: projects/${PROJECT_ID}/secrets/CALENDSO_ENCRYPTION_KEY/versions/1
          env: CALENDSO_ENCRYPTION_KEY
        - versionName: projects/${PROJECT_ID}/secrets/DATABASE_URL/versions/1
          env: DATABASE_URL
        - versionName: projects/${PROJECT_ID}/secrets/EMAIL_SERVER_PASSWORD/versions/1
          env: EMAIL_SERVER_PASSWORD
        - versionName: projects/${PROJECT_ID}/secrets/EMAIL_SERVER_USER/versions/1
          env: EMAIL_SERVER_USER
        - versionName: projects/${PROJECT_ID}/secrets/GOOGLE_API_CREDENTIALS/versions/1
          env: GOOGLE_API_CREDENTIALS
        - versionName: projects/${PROJECT_ID}/secrets/NEXTAUTH_SECRET/versions/1
          env: NEXTAUTH_SECRET
        - versionName: projects/${PROJECT_ID}/secrets/CRON_API_KEY/versions/1
          env: CRON_API_KEY
        - versionName: projects/${PROJECT_ID}/secrets/ZOOM_CLIENT_ID/versions/1
          env: ZOOM_CLIENT_ID
        - versionName: projects/${PROJECT_ID}/secrets/ZOOM_CLIENT_SECRET/versions/1
          env: ZOOM_CLIENT_SECRET

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/stark-tech/${REPO_NAME}/${BRANCH_NAME}/${COMMIT_SHA}',
      ]

  # deploy to cloud run, timeout and environment variables
  #- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #  entrypoint: 'gcloud'
  #  timeout: 240s
  #  args:
  #    [
  #      'compute',
  #      'instances',
  #      'create-with-container',
  #      'my-vm-name',
  #      '--container-image',
  #      'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/stark-tech/${REPO_NAME}/${BRANCH_NAME}/${COMMIT_SHA}',
  #    ]
  #  env:
  #    - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  #    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
